services:
  api:
    build:
      context: ./server
    container_name: flo-api
    expose:
      - "4000"
    environment:
      - NODE_ENV=production
      - PORT=4000

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://api:4000
    container_name: flo-frontend
    ports:
      - "8080:8080"
    environment:
      - VITE_API_BASE_URL=http://api:4000
    depends_on:
      - api
