services:
  api:
    build:
      context: ./server
    container_name: flo-api
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000

  frontend:
    build:
      context: ./frontend
    container_name: flo-frontend
    ports:
      - "8080:8080"
    environment:
      - VITE_API_BASE_URL=http://localhost:4000
